---
collections:
  - name: ansible.posix
  - name: community.general
  - name: containers.podman
  # Don't use this for 2.5
  #- name: infra.controller_configuration
  - name: awx.awx
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.eda
  - name: infra.aap_configuration
    version: 3.1.0
  - name: ansible.controller
    version: 4.6.7
