- hosts: localhost
  connection: local
  gather_facts: false

  vars:

    # Format for 2.4
#    controller_username: "admin"
#    controller_password: "d3v0ps"
#    controller_hostname: "s25-aap.sys.cigna.com"
#    controller_validate_certs: false

    # Format for 2.5
    aap_username: "admin"
    aap_password: "d3v0ps"
    aap_hostname: "s25-aap.sys.cigna.com"
    aap_validate_certs: false
    
  
  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: "{{ dispatch_input_path }}"
        ignore_files: [controller_config.yml.template]
        extensions: ["yaml"]
        ignore_unknown_extensions: true

  roles:

    # This is for 2.4
    #- role: infra.controller_configuration.dispatch
    
    # This is for 2.5 
    - role: infra.aap_configuration.dispatch
      vars: 
        gateway_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: aap_organizations
            tags: organizations
            assign_galaxy_credentials_to_org: false
            assign_default_ee_to_org: false
            assign_notification_templates_to_org: false

        controller_configuration_dispatcher_roles:
          # ORDER MATTERS!!!
#          - role: controller_credential_types
#            var: controller_credential_types
#            tags: credential_types
#          - role: controller_credentials
#            var: controller_credentials
#            tags: credentials
          - role: controller_projects
            var: controller_projects
            tags: projects
            ignore_errors: true
          - role: controller_inventories
            var: controller_inventories
            tags: inventories
          - role: controller_inventory_sources
            var: controller_inventory_sources
            tags: inventory_sources
          - role: controller_job_templates
            var: controller_templates
            tags: job_templates
          - role: controller_workflow_job_templates
            var: controller_workflows
            tags: workflow_job_templates
