- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - name: Load vault vars
      ansible.builtin.include_vars:
        file: vault/vault.yml
      no_log: "{{ secure_logging }}"

  tasks:

    - name: Clone the resource repo for {{ organization_id }} 
      ansible.builtin.include_role:
        name: setup 

#    - name: Sanitize the source files
#      ansible.builtin.include_role:
#        name: sanitize_resource_files
#
#    - name: Import the organization's resources
#      ansible.builtin.import_role:
#        name: infra.controller_configuration.filetree_create
#      vars:
#        output_path: "{{ filetree_create_output_path }}"
#        # Don't specify schedules if exporting a single org or else all schedules will be exported
#        input_tag: ['labels', 'applications', 'inventory', 'notification_templates', 'organizations', 'projects', 'execution_environments', 'job_templates', 'workflow_job_templates']
#        flatten_output: true
#
#    - name: Upload resources for the next stage
#      ansible.builtin.include_role:
#        name: upload_resource_exports
