---
collections:
  - name: ansible.posix
  - name: community.general
  - name: containers.podman
  # Don't use this for 2.5
  #- name: infra.controller_configuration
  - name: awx.awx
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.eda
  - name: ansible.controller
    #version: 4.6.7
    version: 4.6.12
roles:
  - name: infra.aap_configuration
    #version: 3.1.0
    #version: 3.2.0
    version: 3.3.0
